### ISSUE TITLE
Please Release  Your Manga Website Source Code

### ISSUE THREAD

**Issue by healer-op** [adithyaanil1999/manga-reader-express#1]
Please Release  Your Manga Website Source Code,
Hey! I was Really Interested in Your Manga Website and I am new to web scraping please make your
https://adithyaanil1999.github.io/manga-reader-ang
source public with installation docs.

Thank You So Much

**Comment by adithyaanil1999** [comment]
Sure, its been nearly a year anyway and there isnt anything more I need to add, but do inform me if you intend to use it for any commercial/monetary purpose. Also I will not release the backend server used for user account management for obvious reasons.

There isnt is a documentation because its something I made for fun during COVID, just run npm install and then npm run start in the src directory

**Comment by healer-op** [comment]
I am not releasing as a commercial product I just want to improve my knowledge on web scraping and ejs as your are using, I love to learn new stuffs, just want to make a contribution to UI
